name: DQN2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - anaconda
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # comment this out if you don't have a GPU
  - astroid
  - box2d-py
  - cloudpickle
  - contourpy
  - cycler
  - dill
  - farama-notifications
  - fonttools
  - gym
  - gym-notices
  - gymnasium
  - isort
  - joblib
  - kiwisolver
  - matplotlib
  - mccabe
  - pandas
  - pygame
  - pylint
  - pyparsing
  - pytz
  - scikit-learn
  - seaborn
  - swig
  - threadpoolctl
  - tomli
  - tomlkit
  - typeguard
  - tzdata